#!/usr/bin/env bash
#Displays information about subdomains

function subdomain() {
	ANS=$(dig $1 | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
	DOMAIN=$(echo $ANS | cut -d ' '  -f 1 | cut -d '.' -f 1)
	TYPE=$(echo $ANS | cut -d ' ' -f 4)
	IP=$(echo $ANS | cut -d ' ' -f 5 )
	echo "The subdomain $DOMAIN is a $TYPE record and points to $IP"
}

my_sub=('www' 'lb-01' 'web-01' 'web-02')
if [ $# -eq 1 ]; then
	sub=$(echo $1 | cut -d "." -f 1)
	for element in "${my_sub[@]}"; do
		if [[ "$element" == "$sub" ]]; then
			subdomain $1
			exit 0
		fi
	done

	for element in "${my_sub[@]}"; do
		subdomain "$element.$1"
	done
else
	subdomain "$2.$1"
	exit 0
fi
