#!/usr/bin/env bash
# make nginx point to port 80
sudo apt-get update
sudo apt-get install -y nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nignx/sites-enabled/default
sudo service nginx restart
