#!/usr/bin/env bash
#replace nginx with new user nginx
sudo useradd -r -s /sbin/nologin nginx
sudo sed -i "s/#user www-data/c\user nginx" /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /var/log/nginx
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
