#!/usr/bin/env bash
#replace nginx with new user nginx
sudo useradd -r -s /sbin/nologin nginx
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
